### ISSUE TITLE
Issues are dramaticized

### ISSUE THREAD

**Issue by Quenty** [Narrev/How-Quenty-Scripts#2]
My scripting isn't _that_ bad. :(

Furthermore, some of the code you're basing this off of is 3-4 years old at this point.

**Comment by Narrev** [comment]
It's just a joke. You obviously are a good scripter and I wouldn't have made this otherwise. It's just funny to me how your style is very different yet completely consistent and you're habits are uniform across scripts. I threw this together in 5 minutes to amuse you, not to critique or make you feel bad about your scripting. 

The issues are dramatized to make them obvious

**Comment by Quenty** [comment]
Of course it is 😄. I really appreciate the work you put into my other projects Narrev.

 I thought it'd be fun to file this is a bug, whereas of _course_ these are real and genuine issues with the codebase. 

The other issues I filed, for the most part, are actual things I think are important (see #1), because they affect code stability and there is justification for behavior.
